app = "kaspi-dmp-frontend"
primary_region = "waw"

[build]
  dockerfile = "frontend/Dockerfile"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
