app = "kaspi-dmp-backend"
primary_region = "waw"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  TZ = "Asia/Almaty"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
