name: Deploy Frontend
on:
  push:
    branches: [ main ]
    paths: [ 'frontend/**', 'fly.frontend.toml', '.github/workflows/deploy-frontend.yml' ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1
      - name: Deploy FE
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy -c fly.frontend.toml --remote-only
