name: Deploy Backend
on:
  push:
    branches: [ main ]
    paths: [ 'backend/**', 'fly.backend.toml', '.github/workflows/deploy-backend.yml' ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FLY_ORG: personal    # если есть команда — поставь её slug вместо personal
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Debug auth/org
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          set -euxo pipefail
          flyctl auth whoami
          flyctl orgs list
          flyctl apps list || true

      - name: Ensure app exists
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          set -euxo pipefail
          APP=$(awk -F\" '/^app =/{print $2}' fly.backend.toml)
          ORG="${FLY_ORG:-personal}"
          echo "Target app: $APP (org: $ORG)"
          if flyctl apps show "$APP" >/dev/null 2>&1; then
            echo "✅ App $APP already exists"
          else
            flyctl apps create "$APP" --org "$ORG"
          fi

      - name: Deploy API
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: flyctl deploy -c fly.backend.toml --remote-only
